### ISSUE TITLE
`AssertionError: openbsd6` when starting coq

### ISSUE THREAD

**Issue by icyphox** [ms-jpq/coq_nvim#116]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/__main__.py", line 152,
 in <module>
    from .client import CoqClient
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/client.py", line 26, in
 <module>
    from .server.runtime import stack
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/server/runtime.py", lin
e 16, in <module>
    from ..clients.t9.worker import Worker as T9Worker
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/clients/t9/worker.py",
line 22, in <module>
    from .install import T9_BIN, ensure_updated
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/clients/t9/install.py",
 line 14, in <module>
    from std2.platform import OS, os
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/.vars/runtime/lib/python3.8
/site-packages/std2/platform.py", line 22, in <module>
    os = _os()
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/.vars/runtime/lib/python3.8
/site-packages/std2/platform.py", line 19, in _os
    assert False, platform
AssertionError: openbsd6
```

This is the traceback I get. I'm running OpenBSD. Looks like this is Tabnine(?); can it be disabled?

**Comment by ms-jpq** [comment]
wtf, ok ill push a fix once i get up, i wrote my os detection code and did not expect bsd to be a thing, so i did an assert false there, apparently im an idiot and people do use bsd.

**Comment by icyphox** [comment]
No worries, lmao. And yes, there's always that one guy using the most obscure setup.

**Comment by ms-jpq** [comment]
sorry still in bed, did some drinking last night lol

**Comment by icyphox** [comment]
Don't worry about it. I'm chilling this weekend too, heh.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/118

please pull latest :), though tabnine will not work, i dont think they support any bsd variants

**Comment by icyphox** [comment]
Awesome! And I don't really care, I don't use Tabnine.

**Comment by icyphox** [comment]
Oops, sorry. Doesn't look like it's fixed:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/__main__.py", line 152,
 in <module>
    from .client import CoqClient
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/client.py", line 26, in
 <module>
    from .server.runtime import stack
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/server/runtime.py", lin
e 16, in <module>
    from ..clients.t9.worker import Worker as T9Worker
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/clients/t9/worker.py",
line 22, in <module>
    from .install import T9_BIN, ensure_updated
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/coq/clients/t9/install.py",
 line 15, in <module>
    from std2.platform import OS, os
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/.vars/runtime/lib/python3.8
/site-packages/std2/platform.py", line 29, in <module>
    os = _os()
  File "/home/icy/.local/share/nvim/site/pack/paqs/start/coq_nvim/.vars/runtime/lib/python3.8
/site-packages/std2/platform.py", line 26, in _os
    assert False, sys
AssertionError: openbsd
```

I now get an `AssertionError: openbsd`, (not `openbsd6`).

**Comment by ms-jpq** [comment]
OHHHHHH, openBSD...

sorry I tested on FreeBSD, i thought they were the same thing!. ok ill push sorry about that

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/119

sorry sorry its now updated for openbsd too

**Comment by icyphox** [comment]
Ayy thanks! Works amazing.
