### ISSUE TITLE
Error with `null-ls` lsp

### ISSUE THREAD

**Issue by mcchrish** [ms-jpq/coq_nvim#167]
```
Error executing lua: [string "<nvim>"]:36: attempt to index local 'ctx' (a number value)
Traceback (most recent call last):
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/logging.py", line 31
, in with_suppress
    yield None
  File "nvim/site/pack/packer/start/coq_nvim/coq/shared/runtime.py", line 135, in supervise
    async for completion in worker.work(context):
  File "nvim/site/pack/packer/start/coq_nvim/coq/clients/lsp/worker.py", line 81, in work
    async for src, lsp_comps in stream():
  File "nvim/site/pack/packer/start/coq_nvim/coq/clients/lsp/worker.py", line 75, in stream
    yield await fut
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one

    return f.result()  # May raise f.exception().
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/std2/_prelude.py", line 30, in
 anext
    return await ait.__anext__()
  File "nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/completion.py", line 26, in request
    async for reply in async_request(nvim, "COQlsp_comp", (row, col)):
  File "nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/request.py", line 47, in async_request
    await async_call(nvim, cont)
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 83, in
 async_call
    return await loop.run_in_executor(None, fut.result)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in ru
n
    result = self.fn(*self.args, **self.kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in re
sult
    return self.__get_result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __
get_result
    raise self._exception
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 74, in
 cont
    ret = fn(*args, **kwargs)
  File "nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/request.py", line 45, in cont

  File "nvim/site/pack/packer/start/coq_nvim/coq/clients/lsp/worker.py", line 81, in work
    async for src, lsp_comps in stream():
  File "nvim/site/pack/packer/start/coq_nvim/coq/clients/lsp/worker.py", line 75, in stream
    yield await fut
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one

    return f.result()  # May raise f.exception().
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/std2/_prelude.py", line 30, in
 anext
    return await ait.__anext__()
  File "nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/completion.py", line 26, in request
    async for reply in async_request(nvim, "COQlsp_comp", (row, col)):
  File "nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/request.py", line 47, in async_request
    await async_call(nvim, cont)
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 83, in
 async_call
    return await loop.run_in_executor(None, fut.result)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in ru
n
    result = self.fn(*self.args, **self.kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in re
sult
    return self.__get_result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __
get_result
    raise self._exception
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 74, in
 cont
    ret = fn(*args, **kwargs)
  File "nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/request.py", line 45, in cont
    nvim.api.exec_lua(f"{method}(...)", (method, session, *args))
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182,
 in request
    res = self._session.request(name, *args, **kwargs)
  File "nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py"
, line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Error executing lua: [string "<nvim>"]:36: attempt to index local 'ctx' (a number value)
```

https://github.com/jose-elias-alvarez/null-ls.nvim

It used to work without a problem.

Only happens with a lua file.

LspInfo:
```
 1 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [1])
 	filetypes:       lua, javascript, javascriptreact, typescript, typescriptreact, vue, svelte, css, scss, html, json, yaml, markdown
 	autostart:       false
 	root directory:  /Users/mcchris/.dotfiles
 	cmd:             nvim
```

Meanwhile it works when the buffer have **another** LSP alongside `null-ls`.

**Comment by zfogg** [comment]
+1

**Comment by doums** [comment]
+1

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/169

sorry, its should be fixed.

what went wrong was that there is a breaking change to `nvim`'s `LSP` api [coming in 5.1](https://github.com/neovim/neovim/pull/15504), I tried to be cute and avoid version detection by counting how many parameters a certain function receives, turns out, for `null-ls`, the existing API sends 1 less argument than expected.

**Comment by ms-jpq** [comment]
ok I just pushed another commit, that also tries to be cute and avoid version detection, but uses a type check instead, fingers crossed.

I just really hate version checks lol.

**Comment by ms-jpq** [comment]
oh boy it looks like I have to version detection after all

**Comment by mjlbach** [comment]
sorry :cry:

**Comment by ms-jpq** [comment]
hahah dw! thanks for letting us know about the change, better this than broken randomly at 2AM lol
