### ISSUE TITLE
Unique constraint failed: files.filename

### ISSUE THREAD

**Issue by Nis5l** [ms-jpq/coq_nvim#181]
After running COQnow i get this error.
I'm running the latest version from the coq branch.
I've tried reinstalling.
```
UNIQUE constraint failed: files.filename
Traceback (most recent call last):
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\logging.py", line 31, in with_suppress
    yield None
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\lib.py", line 43, in wrapper
    return await aw
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\tags\worker.py", line 149, in _poll
    await self._misc.reconciliate(dead, new=new)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\databases\tags\database.py", line 106, in reconciliate
    await run_in_executor(self._ex.submit, cont)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\std2\asyncio\_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\executor.py", line 33, in submit
    return cast(T, fut.result())
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\executor.py", line 24, in cont
    ret = f(*args, **kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\databases\tags\database.py", line 103, in cont
    cursor.executemany(sql("insert", "file"), m1())
sqlite3.IntegrityError: UNIQUE constraint failed: files.filename
```

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/182

sorry, I did a windows path normalization and forgot to check for both insertion and deletion,

**Comment by ms-jpq** [comment]
didnt catch it because unix filenames dont need to be normalized, and therefore the normalization had zero effect.

**Comment by Nis5l** [comment]
After updating to the latest commit I now get:
```
FOREIGN KEY constraint failed
Traceback (most recent call last):
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\logging.py", line 31, in with_suppress
    yield None
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\lib.py", line 43, in wrapper
    return await aw
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\tags\worker.py", line 149, in _poll
    await self._misc.reconciliate(dead, new=new)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\databases\tags\database.py", line 106, in reconciliate
    await run_in_executor(self._ex.submit, cont)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\std2\asyncio\_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\executor.py", line 33, in submit
    return cast(T, fut.result())
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\executor.py", line 24, in cont
    ret = f(*args, **kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\databases\tags\database.py", line 104, in cont
    cursor.executemany(sql("insert", "tag"), m2())
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by ms-jpq** [comment]
oh wow sorry, I missed a spot :<, just pushed it

**Comment by Nis5l** [comment]
It now works for the first time executing COQnow, but after restarting and running it again I get:
```
UNIQUE constraint failed: files.filename
Traceback (most recent call last):
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\logging.py", line 31, in with_suppress
    yield None
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\lib.py", line 43, in wrapper
    return await aw
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\tags\worker.py", line 149, in _poll
    await self._misc.reconciliate(dead, new=new)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\databases\tags\database.py", line 106, in reconciliate
    await run_in_executor(self._ex.submit, cont)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\std2\asyncio\_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\executor.py", line 33, in submit
    return cast(T, fut.result())
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\executor.py", line 24, in cont
    ret = f(*args, **kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\databases\tags\database.py", line 103, in cont
    cursor.executemany(sql("insert", "file"), m1())
sqlite3.IntegrityError: UNIQUE constraint failed: files.filename

```

**Comment by ms-jpq** [comment]
wtf man, im so sorry, i really need a windows test machine.

**Comment by ms-jpq** [comment]
lol ive been pushing it out blind and hoping it got them all

**Comment by Nis5l** [comment]
No problem, take your time. :D

**Comment by ms-jpq** [comment]
im really sorry about the bad windows support, like I really dont have a windows test machine, but I just made another push, can you kindly test it.

I think i might have gotten the last one

**Comment by ms-jpq** [comment]
wait, reeeeeeee, ok now

**Comment by ms-jpq** [comment]
I didn't want to invalidate your DB, but now that there has been different paths inserted, i wasnt confident that it wasn't gonna cause issue, I just invalidated it and it should rebuild incrementally as you open different files again

**Comment by Nis5l** [comment]
Okay, seems like everything is working now, thanks.
Great plugin by the way.

**Comment by ms-jpq** [comment]
thank you for the patience.

**Comment by Nis5l** [comment]
Just got this one:
```
[WinError 3] The system cannot find the path specified: 'C:\\ '
Traceback (most recent call last):
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\logging.py", line 31, in with_suppress
    yield None
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\shared\runtime.py", line 135, in supervise
    async for completion in worker.work(context):
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\paths\worker.py", line 223, in work
    seq = await co
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\paths\worker.py", line 165, in _parse
    return await run_in_executor(cont)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\.vars\runtime\lib\site-packages\std2\asyncio\_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\paths\worker.py", line 152, in cont
    return {
  File "C:\Program Files\Neovim\share\nvim\plugged\coq_nvim\coq\clients\paths\worker.py", line 114, in parse
    for path in entire.iterdir():
  File "C:\Users\kirch\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1150, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ '
```

**Comment by ms-jpq** [comment]
sorry can you try now?

**Comment by ms-jpq** [comment]
paths under windows is still broken though, right now it has zero drive handling, i guess ill add it in the next pr

**Comment by ms-jpq** [comment]
ok added drive handling too

**Comment by Nis5l** [comment]
Thanks, seems to work.

**Comment by ms-jpq** [comment]
haha i hope its the last of issues. <3
