### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc2'

### ISSUE THREAD

**Issue by nathom** [ms-jpq/coq_nvim#19]
When using coq with trouble.nvim, I'm getting this error any time I press a key.

Traceback:

```
'utf-8' codec can't encode character '\udcc2' in position 195: surrogates not allowed
Traceback (most recent call last):
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/logging.py", line 31, in with_suppress
    yield None
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/registrants/attachment.py", line 56, in cont
    await stack.bdb.set_lines(
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/databases/buffers/database.py", line 143, in set_lines
    await run_in_executor(self._ex.submit, cont)
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/std2/asyncio/_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "/Users/nathan/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/executor.py", line 33, in submit
    return cast(T, fut.result())
  File "/Users/nathan/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/nathan/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/executor.py", line 24, in cont
    ret = f(*args, **kwargs)
  File "/Users/nathan/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/databases/buffers/database.py", line 128, in cont
    cursor.executemany(sql("insert", "line"), m1())
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc2' in position 195: surrogates not allowed
Press ENTER or type command to continue
```

**Comment by nathom** [comment]
It looks like the issue is with these devicons, which python is trying to encode as utf-8. Maybe adding something that ignores buffer names without file extensions will fix the issue.

<img width="48" alt="image" src="https://user-images.githubusercontent.com/74019033/129484949-a6845b55-1fc0-43b2-a66c-928a2f7111e5.png">

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/25

I think I fixed it, please pull newest
