### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by wizard-28** [ms-jpq/coq_nvim#222]
When I type (after each key stoke while in `insert` mode), I get this error
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime
/lua/vim/uri.lua:116: attempt to index local 'uri' (a nil value)
```

**Comment by ms-jpq** [comment]
humm can you please post your nvim version, i suspect its an upstream LSP client error, might help if you disable LSP client for now.

thanks :)

**Comment by wizard-28** [comment]
> humm can you please post your nvim version

Yeah sure, here it is
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-86eex6/neovim-0.6.0~ubuntu1+git202109051200-dce50312e-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-86eex6/neovim-0.6.0~ubuntu1+git202109051200-dce50312e-adeb5640f/build/config -I/build/neovim-86eex6/neovim-0.6.0~ubuntu1+git202109051200-dce50312e-adeb5640f/src -I/build/neovim-86eex6/neovim-0.6.0~ubuntu1+git202109051200-dce50312e-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-86eex6/neovim-0.6.0~ubuntu1+git202109051200-dce50312e-adeb5640f/build/src/nvim/auto -I/build/neovim-86eex6/neovim-0.6.0~ubuntu1+git202109051200-dce50312e-adeb5640f/build/include
Compiled by buildd@lcy01-amd64-024

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

---

> i suspect its an upstream LSP client error, might help if you disable LSP client for now.

I was using the `bash` LSP when this happened, I opened a python file ( with the `pyright` LSP running), and the error didn't occur. Thanks

**Comment by zeertzjq** [comment]
Try recompiling Neovim master. (<https://github.com/neovim/neovim/pull/15504>)

**Comment by ms-jpq** [comment]
can you please try pulling latest and see if it helps :D 

there was a PR that fixed some breaking changes due to upstream API update.

**Comment by wizard-28** [comment]
The last error is gone, but now I get a new error
```
end_col out of bounds
EditInstruction(primary=True, begin=(300, 0), end=(300, 4), cursor_yoffset=0, cursor_xpos=10, new_lines=['checkpoint'])
start_col out of bounds
Traceback (most recent call last):
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/logging.py", l
ine 31, in with_suppress
    yield None
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line
43, in wrapper
    return await aw
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/coq/server/registrants/omnifunc.py", line 224, in cont
    await async_call(nvim, cont)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line
83, in async_call
    return await loop.run_in_executor(None, fut.result)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line
74, in cont
    ret = fn(*args, **kwargs)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/coq/server/registrants/omnifunc.py", line 220, in cont
    inserted = edit(nvim, stack=stack, state=s, data=ud)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/coq/server/edit.py", line 422, in edit
    buf_set_text(
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/api.py", line
286, in buf_set_text
    nvim.api.buf_set_text(buf, r1, c1, r2, c2, text)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/api/nvim.py", lin
e 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/msgpack_rpc/sessi
on.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: start_col out of bounds
```

This error doesn't happen every time, it happens only when I try to edit the completion (and I kind of have to do it many times to trigger it)

For example:
1. I type this first
```
che
```

---

2. Then I auto complete (tab) it to
```
checkpoint
```

---

3. Then I try to backspace back to
```
che
```

---

4. Then I again try to tab complete it. Then that error occurs. (This only happens seldom)

I've only noticed this error with the `bash` LSP for now. This doesn't occur with the `python` LSP, as far as I've noticed.

**Comment by ms-jpq** [comment]
ok i added like a small thingy for it, can you please try again,


^_^, thanks.

**Comment by wizard-28** [comment]
It doesn't seem to occur anymore. Thanks.
