### ISSUE TITLE
Cursor position outside buffer

### ISSUE THREAD

**Issue by wizard-28** [ms-jpq/coq_nvim#240]
I was browsing through the suggestions (tabbing one by one) when this error occurred. This error happened when the `shebang` snippet was highlighted (in the popup menu) in a bash file.

## Error
```py
Cursor position outside bufferlines=['#!/bin/sh', ''])
Traceback (most recent call last):
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/logging.py"
, line 31, in with_suppress
    yield None
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", li
ne 43, in wrapper
    return await aw
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/coq/server/registrants/omnifunc.py", line 224, in cont
    await async_call(nvim, cont)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", li
ne 83, in async_call
    return await loop.run_in_executor(None, fut.result)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57,
 in run
 in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444,
 in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389,
 in __get_result
    raise self._exception
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", li
ne 74, in cont
    ret = fn(*args, **kwargs)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/coq/server/registrants/omnifunc.py", line 220, in cont
    inserted = edit(nvim, stack=stack, state=s, data=ud)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/coq/server/edit.py", line 443, in edit
    win_set_cursor(nvim, win=win, row=n_row, col=n_col)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/api.py", li
ne 242, in win_set_cursor
    nvim.api.win_set_cursor(win, (row + 1, col))
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim/api/nvim.py",
line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/pop-os/.local/share/nvim/site/pack/packer/opt/coq_nv
im/.vars/runtime/lib/python3.8/site-packages/pynvim/msgpack_rpc/se
ssion.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Cursor position outside buffer
```

## Neovim version
```py
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-dUgx9z/neovim-0.6.0~ubuntu1+git202109071155-db695cc4c-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-dUgx9z/neovim-0.6.0~ubuntu1+git202109071155-db695cc4c-adeb5640f/build/config -I/build/neovim-dUgx9z/neovim-0.6.0~ubuntu1+git202109071155-db695cc4c-adeb5640f/src -I/build/neovim-dUgx9z/neovim-0.6.0~ubuntu1+git202109071155-db695cc4c-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-dUgx9z/neovim-0.6.0~ubuntu1+git202109071155-db695cc4c-adeb5640f/build/src/nvim/auto -I/build/neovim-dUgx9z/neovim-0.6.0~ubuntu1+git202109071155-db695cc4c-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-037

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
I'm using the latest `coq_nvim` ( `coq` branch) and `coq.artifacts` ( `artifacts` branch )

**Comment by zeertzjq** [comment]
Did you insert the suggestion?

**Comment by wizard-28** [comment]
No. I don't remember inserting it. Not sure though.

**Comment by ms-jpq** [comment]
yeah there was an insertion, because `edit` was called.

so I think this might one one of those rare cases where the user made a change inbetween `coq` applying updates. 

I added a `try -> log` around it, so its not too annoying for now, but unless we store the entire state of the page, things like this will be hard to solve

**Comment by jdefez** [comment]
I think i'm in the same situation. But it freezes every time a completion is triggered.

![Screenshot 2022-09-21 at 09 05 29](https://user-images.githubusercontent.com/624058/191437625-0c62cff9-471f-46d4-a9c9-aabb6ed2c7cc.png)

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```
