### ISSUE TITLE
Windows 10 terminal error

### ISSUE THREAD

**Issue by Nis5l** [ms-jpq/coq_nvim#268]
I get this error when working with a terminal (:terminal) in Windows 10.
```
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\logging.py", line 31, in with_suppress
    yield None
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\.vars\runtime\lib\site-packages\pynvim_pp\lib.py", line 54, in wrapper
    return await aw
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\clients\tags\worker.py", line 141, in _poll
    mtimes = await _mtimes(paths)
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\clients\tags\worker.py", line 51, in _mtimes
    return await run_in_executor(c2)
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\.vars\runtime\lib\site-packages\std2\asyncio\_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\clients\tags\worker.py", line 50, in <lambda>
    c2 = lambda: {normcase(key): val for key, val in c1()}
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\clients\tags\worker.py", line 50, in <dictcomp>
    c2 = lambda: {normcase(key): val for key, val in c1()}
  File "C:\Users\xxxx\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\clients\tags\worker.py", line 47, in c1
    stat = path.stat()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1222, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'term:\\~\\OneDrive\\Dokumente\\yyyy\\7336:C:\\Windows\\system32\\cmd.exe'
```

**Comment by ms-jpq** [comment]
god i hate it, just when u think u got all the windows stuff, ok will gib a quick fix

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/269
