### ISSUE TITLE
`client_id: expected number, got nil`

### ISSUE THREAD

**Issue by jesse-c** [ms-jpq/coq_nvim#293]
I'm currently up-to-date and I've just begun seeing this:

```
Error executing lua: [string "<nvim>"]:62: client_id: expected number, got nil
stack traceback:
        [string "<nvim>"]:62: in function 'on_resp_old'
        [string "<nvim>"]:82: in function 'handler'
        ...l/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:1277: in function 'callback'
        [string "<nvim>"]:89: in function 'req'
        [string "<nvim>"]:114: in function 'lsp_comp'
        [string "<nvim>"]:1: in main chunk
Traceback (most recent call last):
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/logging.py", line 31, in with_suppre
ss
    yield None
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/runtime.py", line 135, in supervise
    async for completion in worker.work(context):
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/lsp/worker.py", line 80, in work
    async for src, lsp_comps in stream():
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/lsp/worker.py", line 74, in stream
    yield await fut
  File "/Users/jesse/.asdf/installs/python/3.8.2/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/std2/_prelude.py", line 29, in anext
    return await ait.__anext__()
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/completion.py", line 24, in comp_lsp
    async for client, reply in async_request(nvim, "lsp_comp", (row, col)):
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/request.py", line 80, in async_request
    await async_call(nvim, cont)
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 94, in async_call
    return await loop.run_in_executor(None, fut.result)
  File "/Users/jesse/.asdf/installs/python/3.8.2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jesse/.asdf/installs/python/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/jesse/.asdf/installs/python/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 85, in cont
    ret = fn(*args, **kwargs)
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/lsp/requests/request.py", line 78, in cont
    nvim.api.exec_lua(f"{NAMESPACE}.{name}(...)", (name, uid, *args))
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/jesse/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in r
equest
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Error executing lua: [string "<nvim>"]:62: client_id: expected number, got nil
stack traceback:
        [string "<nvim>"]:62: in function 'on_resp_old'
        [string "<nvim>"]:82: in function 'handler'
        ...l/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:1277: in function 'callback'
        [string "<nvim>"]:89: in function 'req'
        [string "<nvim>"]:114: in function 'lsp_comp'
        [string "<nvim>"]:1: in main chunk
```

It's on almost every key press, but not all. E.g. space does, but d doesn't.

I've tried with both Neovim 0.5.0 and HEAD. There's been no changes to my Neovim setup from when this issue started.

It doesn't happen for all filetypes for me. E.g. Elixir is okay.

**Comment by ms-jpq** [comment]
sorry please pull again. i fixed it

**Comment by jesse-c** [comment]
No worries! Thank you for fixing it so quickly, and thank you for coq! Its' working now.

**Comment by williamboman** [comment]
I seem to be running into this with custom sources. https://asciinema.org/a/70kYtIAgkrSiknTGtswkcc2cX

It seems to work prior to dd555b5e11d9a390b5a7baeb60a8dd1d16906260

and here's the custom source impl: https://github.com/williamboman/nvim-config/blob/faf3d8a9a99942269deb473abe1aaba193e5155e/lua/wb/coq_3p/uuid.lua

**Comment by Mte90** [comment]
I am facing the same issue with https://github.com/Mte90/coq_wordpress

**Comment by Mte90** [comment]
Looking at the code on https://github.com/ms-jpq/coq_nvim/blob/4cda35c003e646b5f6bdb312dab70106027fc3e5/coq/lsp/requests/lsp.lua#L62 expect that variable in that way.
But I cannot find the definition of that value somewhere, I see that a sources just need some parameters https://github.com/ms-jpq/coq_nvim/blob/4cda35c003e646b5f6bdb312dab70106027fc3e5/coq/lsp/requests/lsp.lua#L44

So maybe custom sources generate errors because they are not LSP servers or the doc for custom sources wasn't updated with the latest changes.

**Comment by williamboman** [comment]
By now I've forgotten what discoveries I made, but it seems like your onto something. Although - how does the 3p sources work fine but custom ones does not? Don't they use the same APIs?

**Comment by williamboman** [comment]
Perhaps we should continue in a new issue? I'd be happy to create one once I'm back at the 💻
