### ISSUE TITLE
COQdeps returns non-zero status code

### ISSUE THREAD

**Issue by ChrisAmelia** [ms-jpq/coq_nvim#30]
Output of `python3 -V`:

> Python 3.9.6

Also tried with `Python 3.8.11`, same result.

```
Traceback (most recent call last):                                                                                                                                                                                            
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                                                                                                                          
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/share/nvim/site/pack/packer/opt/coq_nvim/coq/__main__.py", line 58, in <module>
    EnvBuilder(
  File "/usr/lib/python3.9/venv/__init__.py", line 75, in create
    self._setup_pip(context)
  File "/usr/lib/python3.9/venv/__init__.py", line 298, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/user/.local/share/nvim/site/pack/packer/opt/coq_nvim/.vars/runtime/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Comment by aprowe** [comment]
I was able to fix this by doing `apt install python3.8-venv`

**Comment by ms-jpq** [comment]
yeah @aprowe  is right.

I had a really confusing error message there, but I have added a better one.

https://github.com/ms-jpq/coq_nvim/pull/54

**Comment by Davidemonaco** [comment]
same issue but on windows, how am i supposed to install python3-env?
