### ISSUE TITLE
Override coq sqlite version?

### ISSUE THREAD

**Issue by ristillu** [ms-jpq/coq_nvim#392]
I am trying to get coq running but there are some hardcoded paths that are tripping me up. My system configuration has an old version of `/usr/bin/sqlite3` and some hard system dependencies on that being installed (such as yum and systemd). I built a sqlite3 version 3.36.0  and installed it in `/usr/local/` (which is a preferred path to `/usr/` for me). On the command line `sqlite3 --version` works fine and tells me 3.36.0.

I am using python 3.10 built from source. I'm using neovim built from source daily.

When I install coq and run `:COQdeps` and then `:COQnow` I get the same message every time about `deterministic=True requires SQLite 3.8.3 or higher`, invoked from `~/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/sqlite3.py`

I have uninstalled and reinstalled COQ many times (including ensuring I blow away the complete packer directory with .vars and everything else).

I cloned the COQ repo and searched for somewhere I might be able to override my sqlite3 path or other relevant paths but I couldn't find what I was looking for.

I repeated the whole process of installing sqlite but put it in `/usr/`, overriding my system sqlite completely (after backing it up) but that didn't help.

Can you tell me how I might tell COQ where to find my updated sqlite3?

**Comment by ristillu** [comment]
Some examples of my environment after completely overwriting my system sqlite installation:
```
[user@host ~]$ python3
Python 3.10.0 (default, Oct  8 2021, 17:39:36) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.36.0'
>>> exit()
[user@host ~]$ sqlite3 --version
3.36.0 2021-06-18 18:36:39 5c9a6c06871cb9fe42814af9c039eb6da5427a6ec28f187af7ebfb62eafa66e5
[user@host ~]$ ll /usr/bin/sqlite3
.rwxr-xr-x root root 8.3 MB Wed Nov 10 17:10:15 2021  /usr/bin/sqlite3
[user@host ~]$ ll /usr/lib64/libsqlite*
.rw-r--r-- root root  14 MB Wed Nov 10 17:10:15 2021  /usr/lib64/libsqlite3.a
.rwxr-xr-x root root 959 B  Wed Nov 10 17:10:15 2021  /usr/lib64/libsqlite3.la
lrwxrwxrwx root root  19 B  Wed Nov 10 17:10:15 2021  /usr/lib64/libsqlite3.so ⇒ libsqlite3.so.0.8.6
lrwxrwxrwx root root  19 B  Wed Nov 10 17:10:15 2021  /usr/lib64/libsqlite3.so.0 ⇒ libsqlite3.so.0.8.6
.rwxr-xr-x root root 5.5 MB Wed Nov 10 17:10:15 2021  /usr/lib64/libsqlite3.so.0.8.6
```
And then I run neovim without COQ, add COQ (using packer) and do `:COQdeps` and `:COQnow` and get
```
[user@host ~]$ nv test.py
deterministic=True requires SQLite 3.8.3 or higher
Traceback (most recent call last):
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/client.py", line 98, in wait
    succ = threadsafe_call(nvim, cont)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/lib.py", line 74, in threadsafe_call
    return cast(_T, fut.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/lib.py", line 65, in cont
    ret = fn(*args, **kwargs)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/client.py", line 76, in cont
    self._stack = stack(self._pool, nvim=nvim)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/runtime.py", line 100, in stack
    BDB(pool),
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/databases/buffers/database.py", line 48, in __init__
    self._conn: Connection = self._ex.submit(_init)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/executor.py", line 33, in submit
    return cast(T, fut.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/executor.py", line 24, in cont
    ret = f(*args, **kwargs)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/databases/buffers/database.py", line 38, in _init
    init_db(conn)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/sql.py", line 78, in init_db
    add_functions(conn)
  File "/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/sqlite3.py", line 54, in add_functions
    conn.create_function("X_STRXFRM", narg=1, func=strxfrm, deterministic=True)
sqlite3.NotSupportedError: deterministic=True requires SQLite 3.8.3 or higher
```

**Comment by ristillu** [comment]
And just to confirm that COQ is picking up the same Python / sqlite3:
```
[user@host bin (coq)]$ pwd
/home/foo.bar/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/bin
[user@host bin (coq)]$ python3.10
Python 3.10.0 (default, Oct  8 2021, 17:39:36) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
[user@host bin (coq)]$ python3
Python 3.10.0 (default, Oct  8 2021, 17:39:36) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
[user@host bin (coq)]$ python
Python 3.10.0 (default, Oct  8 2021, 17:39:36) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.36.0'
>>> 
```

**Comment by ristillu** [comment]
In case anyone else stumbles across this thread, this was nothing to do with COQ. It was my python / sqlite3 setup. I needed to recompile python after manually building/installing sqlite. Even though python was reporting a sufficient sqlite version in those rudimentary tests above, there was a runtime linking error. I figured it out with a bit of help from here: https://comp.lang.python.narkive.com/02W7TdBE/sqlite3-cannot-detect-the-version-of-compiled-sqlite-version-at-some-point-in-runtime

Outside COQ in plain python you could reproduce my problem with:
```
import sqlite3
c = sqlite3.Connection(':memory:')
c.create_function('f', 1, lambda x: x, deterministic=True)
```
and it would raise a NotSupportedError until I recompiled python with my new sqlite3.
