### ISSUE TITLE
Tabnine can't be installed

### ISSUE THREAD

**Issue by michaelb** [ms-jpq/coq_nvim#40]
Hi, I'm currently trying this wonderful plugin, but i'm getting the current error after enabling tabnine and running :COQnow :

```
[Errno 18] Invalid cross-device link: '/tmp/tmpbf8w4pkx' -> '/home/michaelb/.local/share/nvim/plugged/coq_nvim/.vars/cli
ents/t9/TabNine'                                                                                                        
Traceback (most recent call last):                                                                                      
  File "/home/michaelb/.local/share/nvim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/logging.py
", line 31, in with_suppress                                                                                            
    yield None                                                                                                          
  File "/home/michaelb/.local/share/nvim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", l
ine 21, in wrapper                                                                                                      
    return await aw                                                                                                     
  File "/home/michaelb/.local/share/nvim/plugged/coq_nvim/coq/clients/t9/worker.py", line 119, in _install              
    self._installed = await ensure_updated(                                                                             
  File "/home/michaelb/.local/share/nvim/plugged/coq_nvim/coq/clients/t9/install.py", line 77, in ensure_updated        
    await run_in_executor(_update, timeout=timeout)                                                                     
  File "/home/michaelb/.local/share/nvim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/std2/asyncio/_prelud
e.py", line 41, in run_in_executor                                                                                      
    return await loop.run_in_executor(None, cont)                                                                       
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run                                               
    result = self.fn(*self.args, **self.kwargs)                                                                         
  File "/home/michaelb/.local/share/nvim/plugged/coq_nvim/coq/clients/t9/install.py", line 68, in _update               
    Path(fd.name).replace(T9_BIN)                                                                                       
  File "/usr/lib/python3.9/pathlib.py", line 1385, in replace                                                           
    self._accessor.replace(self, target)                                                                                
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpbf8w4pkx' -> '/home/michaelb/.local/share/nvim/plugged/coq_nvim/
.vars/clients/t9/TabNine'
```
I figure that's because I actually use different partition for / and /home and/or have a BTRFS setup, but that should probably be supported. There's usually a cross-device-safe alternative like shutil to in-library methods.

**Comment by ms-jpq** [comment]
So I use a `mv` command after tabnine has been downloaded, to ensure atomicity. The download location is set to basically your `TMP` folder, and it will work for 99% of people.

What happened for you was that your `TMP` folder was located on a different logical disk as where you have installed `coq`, so the `mv` command fails, because its only atomic across the same logical disk.

I just need to update the download path, brb

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/41

done

**Comment by michaelb** [comment]
Works perfectly here as well, thanks again for the amazing plugin and the quick fix!

**Comment by wellcomez** [comment]
> So I use a `mv` command after tabnine has been downloaded, to ensure atomicity. The download location is set to basically your `TMP` folder, and it will work for 99% of people.
> 
> What happened for you was that your `TMP` folder was located on a different logical disk as where you have installed `coq`, so the `mv` command fails, because its only atomic across the same logical disk.
> 
> I just need to update the download path, brb

下载时候报错ssl 证书错误
