### ISSUE TITLE
No module named 'distutils.command.bdist_wininst' during :COQdeps

### ISSUE THREAD

**Issue by Zarainia** [ms-jpq/coq_nvim#420]
I'm getting the following error when running `:COQdeps`:

```
Collecting greenlet
  Using cached greenlet-1.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (155 kB)
Using legacy 'setup.py install' for std2, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pynvim-pp, since package 'wheel' is not installed.
Installing collected packages: msgpack, greenlet, pynvim, std2, PyYAML, pynvim-pp
    Running setup.py install for std2: started
    Running setup.py install for std2: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-58eh8ors/std2_aa4fa45b122a468288275e1864254d35/setup.py'"'"'; __file__='"'"'/tmp/pip-install-58eh8ors/std2_aa4fa45b122a468288275e1864254d35/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5c91tcxs/install-record.txt --single-version-externally-managed --compile --install-headers /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/include/site/python3.10/std2
         cwd: /tmp/pip-install-58eh8ors/std2_aa4fa45b122a468288275e1864254d35/
    Complete output (180 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/std2
    copying std2/aitertools.py -> build/lib/std2
    copying std2/sched.py -> build/lib/std2
    copying std2/functools.py -> build/lib/std2
    copying std2/graphlib.py -> build/lib/std2
    copying std2/platform.py -> build/lib/std2
    copying std2/argparse.py -> build/lib/std2
    copying std2/sqlite3.py -> build/lib/std2
    copying std2/configparser.py -> build/lib/std2
    copying std2/string.py -> build/lib/std2
    copying std2/subprocess.py -> build/lib/std2
    copying std2/coloursys.py -> build/lib/std2
    copying std2/locale.py -> build/lib/std2
    copying std2/lex.py -> build/lib/std2
    copying std2/importlib.py -> build/lib/std2
    copying std2/difflib.py -> build/lib/std2
    copying std2/shutil.py -> build/lib/std2
    copying std2/seq.py -> build/lib/std2
    copying std2/contextlib.py -> build/lib/std2
    copying std2/timeit.py -> build/lib/std2
    copying std2/itertools.py -> build/lib/std2
    copying std2/_prelude.py -> build/lib/std2
    copying std2/urllib.py -> build/lib/std2
    copying std2/pathlib.py -> build/lib/std2
    copying std2/types.py -> build/lib/std2
    copying std2/logging.py -> build/lib/std2
    copying std2/ipaddress.py -> build/lib/std2
    copying std2/datetime.py -> build/lib/std2
    copying std2/statistics.py -> build/lib/std2
    copying std2/__init__.py -> build/lib/std2
    copying std2/unittest.py -> build/lib/std2
    creating build/lib/std2/asyncio
    copying std2/asyncio/subprocess.py -> build/lib/std2/asyncio
    copying std2/asyncio/_prelude.py -> build/lib/std2/asyncio
    copying std2/asyncio/io.py -> build/lib/std2/asyncio
    copying std2/asyncio/__init__.py -> build/lib/std2/asyncio
    copying std2/asyncio/queue.py -> build/lib/std2/asyncio
    creating build/lib/std2/pickle
    copying std2/pickle/encoder.py -> build/lib/std2/pickle
    copying std2/pickle/coders.py -> build/lib/std2/pickle
    copying std2/pickle/decoder.py -> build/lib/std2/pickle
    copying std2/pickle/types.py -> build/lib/std2/pickle
    copying std2/pickle/__init__.py -> build/lib/std2/pickle
    copying std2/py.typed -> build/lib/std2
    running install_lib
    creating /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/aitertools.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/sched.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/functools.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/graphlib.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/platform.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/argparse.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/sqlite3.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/configparser.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    creating /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio
    copying build/lib/std2/asyncio/subprocess.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio
    copying build/lib/std2/asyncio/_prelude.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio
    copying build/lib/std2/asyncio/io.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio
    copying build/lib/std2/asyncio/__init__.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio
    copying build/lib/std2/asyncio/queue.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio
    copying build/lib/std2/string.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/subprocess.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/coloursys.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/locale.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/lex.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/importlib.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/difflib.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/shutil.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/seq.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/contextlib.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/timeit.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/itertools.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/_prelude.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/urllib.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/pathlib.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/types.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/logging.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/ipaddress.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/datetime.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/statistics.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/__init__.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/py.typed -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    copying build/lib/std2/unittest.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2
    creating /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle
    copying build/lib/std2/pickle/encoder.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle
    copying build/lib/std2/pickle/coders.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle
    copying build/lib/std2/pickle/decoder.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle
    copying build/lib/std2/pickle/types.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle
    copying build/lib/std2/pickle/__init__.py -> /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/aitertools.py to aitertools.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/sched.py to sched.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/functools.py to functools.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/graphlib.py to graphlib.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/platform.py to platform.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/argparse.py to argparse.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/sqlite3.py to sqlite3.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/configparser.py to configparser.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio/subprocess.py to subprocess.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio/_prelude.py to _prelude.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio/io.py to io.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/asyncio/queue.py to queue.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/string.py to string.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/subprocess.py to subprocess.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/coloursys.py to coloursys.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/locale.py to locale.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/lex.py to lex.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/importlib.py to importlib.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/difflib.py to difflib.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/shutil.py to shutil.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/seq.py to seq.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/contextlib.py to contextlib.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/timeit.py to timeit.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/itertools.py to itertools.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/_prelude.py to _prelude.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/urllib.py to urllib.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pathlib.py to pathlib.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/types.py to types.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/logging.py to logging.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/ipaddress.py to ipaddress.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/datetime.py to datetime.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/statistics.py to statistics.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/unittest.py to unittest.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle/encoder.py to encoder.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle/coders.py to coders.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle/decoder.py to decoder.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle/types.py to types.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2/pickle/__init__.py to __init__.cpython-310.pyc
    running install_egg_info
    running egg_info
    creating std2.egg-info
    writing std2.egg-info/PKG-INFO
    writing dependency_links to std2.egg-info/dependency_links.txt
    writing top-level names to std2.egg-info/top_level.txt
    writing manifest file 'std2.egg-info/SOURCES.txt'
    reading manifest file 'std2.egg-info/SOURCES.txt'
    writing manifest file 'std2.egg-info/SOURCES.txt'
    Copying std2.egg-info to /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/std2-0.1.10.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-58eh8ors/std2_aa4fa45b122a468288275e1864254d35/setup.py", line 10, in <module>
        setup(
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.10/distutils/command/install.py", line 634, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/setuptools/command/install_scripts.py", line 35, in run
        bw_cmd = self.get_finalized_command("bdist_wininst")
      File "/usr/lib/python3.10/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python3.10/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/setuptools/dist.py", line 834, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/lib/python3.10/site-packages/setuptools/command/bdist_wininst.py", line 1, in <module>
        import distutils.command.bdist_wininst as orig
    ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-58eh8ors/std2_aa4fa45b122a468288275e1864254d35/setup.py'"'"'; __file__='"'"'/tmp/pip-install-58eh8ors/std2_aa4fa45b122a468288275e1864254d35/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5c91tcxs/install-record.txt --single-version-externally-managed --compile --install-headers /home/zarainia/.vim/bundle/coq_nvim/.vars/runtime/include/site/python3.10/std2 Check the logs for full command output.
Installation failed, check :message
COQ EXITED - 1
```

I've verified that `python3-venv` is installed.

**Comment by ms-jpq** [comment]
werid af, i know python 3.10 removed stuff for `pip`, but i didn't know it borked `setup.py`.

and I can't replicate it on CI either. can I ask how is your `python3.10` installed? sometimes distro versions or compiled versions of python from say pyenv would have werid shit

**Comment by Zarainia** [comment]
It's installed through `apt`. This is on WSL with the following Ubuntu version:

```
LSB Version:    core-11.1.0ubuntu3-noarch:security-11.1.0ubuntu3-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```
