### ISSUE TITLE
KeyError after updating deps

### ISSUE THREAD

**Issue by ChewingBever** [ms-jpq/coq_nvim#444]
I just updated my deps to the latest versions on python3.10, but now I'm greeted with this error every time neovim start up:

```
'pattern'
Traceback (most recent call last):
  File "/home/jjr/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/logging.py", line 31, in with_suppress
    yield None
  File "/home/jjr/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/lib.py", line 68, in wrapper
    return await aw
  File "/home/jjr/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/tags/worker.py", line 148, in _poll
    new = parse(mtimes, raw=raw)
  File "/home/jjr/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/tags/parse.py", line 76, in parse
    json["pattern"] = _unescape(json["pattern"])
KeyError: 'pattern'
```

Is this a known issue? And if yes, can it easily be fixed?

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/c9ea3cb9b710a419ad250755e0273eeafa14bcf8
