### ISSUE TITLE
🐞 Bug: [Errno 20] Not a directory: 'ctags'

### ISSUE THREAD

**Issue by npielawski** [ms-jpq/coq_nvim#475]
Every time I open a python file I get the following error:
```bash
Traceback (most recent call last):
  File "/path_to_packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/log
ging.py", line 31, in with_suppress
    yield None
  File "/path_to_packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib
.py", line 68, in wrapper
    return await aw
  File "/path_to_packer/start/coq_nvim/coq/clients/tags/worker.py", line 147, in _poll
    raw = await run(*query_paths) if query_paths else ""
  File "/path_to_packer/start/coq_nvim/coq/tags/parse.py", line 35, in run
    proc = await call(
  File "/path_to_packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/std2/asyncio/
subprocess.py", line 29, in call
    proc = await create_subprocess_exec(
  File "/path_to_miniconda3/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/path_to_miniconda3/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/path_to_miniconda3/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/path_to_miniconda3/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/path_to_miniconda3/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/path_to_miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/path_to_miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'ctags'
```
The OS is Ubuntu 18.04.4 LTS.
Any idea how to fix that?

**Comment by ms-jpq** [comment]
should be fixed now , please reopen if still happens
