### ISSUE TITLE
"sqlite3.OperationalError: locking protocol" error

### ISSUE THREAD

**Issue by jakubgros** [ms-jpq/coq_nvim#478]
Hello. I'm encountering the following error when using COQ:
```
locking protocol
Traceback (most recent call last):
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/client.py", line 98, in wait
    succ = threadsafe_call(nvim, cont)
  File "/home/sg315781/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 88, in threadsafe_call
    return cast(_T, fut.result())
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/sg315781/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 79, in cont
    ret = fn(*args, **kwargs)
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/client.py", line 76, in cont
    self._stack = stack(self._pool, nvim=nvim)
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/server/runtime.py", line 105, in stack
    SDB(pool, vars_dir=vars_dir),
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/databases/snippets/database.py", line 46, in __init__
    self._conn: Connection = self._ex.submit(lambda: _init(db_dir))
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/shared/executor.py", line 35, in submit
    return cast(_T, fut.result())
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/shared/executor.py", line 26, in cont
    ret = f(*args, **kwargs)
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/databases/snippets/database.py", line 46, in <lambda>
    self._conn: Connection = self._ex.submit(lambda: _init(db_dir))
  File "/home/sg315781/.vim/plugged/coq_nvim/coq/databases/snippets/database.py", line 36, in _init
    conn.executescript(sql("create", "pragma"))
sqlite3.OperationalError: locking protocol
```

My setup:
```
WSL with Ubuntu 20.04.4 LTS

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@a1e553b903c7
Features: +acl +iconv +tui

Python version: 3.9.12
pynvim version: 0.4.3

COQ VERSION (not sure how to check it so I checked the commit that I'm currently on):
commit 0a7cc42f0d97d01f2c527c3f62088ff8c91a1e95 

```

Do you have any suggestions how to fix it?

**Comment by jakubgros** [comment]
It seems to be caused by the version of WSL - when I had the issue I was on WSL1, now after updating to WSL2 I didn't observe the issue so far.

**Comment by jakubgros** [comment]
After a week of testing I can confirm that it was the issue and it doesn't appear on WSL2. I'm closing the issue
