### ISSUE TITLE
I'm getting this weird error on pynvim/loggin.py some times on python and lua files, never happened on typescript

### ISSUE THREAD

**Issue by luisiacc** [ms-jpq/coq_nvim#516]
Sometimes when editing files this error should pops up
```
Invalid buffer id: 682
Traceback (most recent call last):
  File "/home/acc/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/logging.py", line 31, in with_suppress
    yield None
  File "/home/acc/.vim/plugged/coq_nvim/coq/clients/tree_sitter/worker.py", line 100, in _poll
    bufs = await async_call(
  File "/home/acc/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/lib.py", line 113, in async_call
    return await nvim.loop.run_in_executor(None, fut.result)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/acc/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/lib.py", line 104, in cont
    ret = fn(*args, **kwargs)
  File "/home/acc/.vim/plugged/coq_nvim/coq/clients/tree_sitter/worker.py", line 21, in _bufs
    bufs = {
  File "/home/acc/.vim/plugged/coq_nvim/coq/clients/tree_sitter/worker.py", line 22, in <dictcomp>
    buf.number: buf_line_count(nvim, buf=buf)
  File "/home/acc/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim_pp/api.py", line 313, in buf_line_count
    count: int = nvim.api.buf_line_count(buf)
  File "/home/acc/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/acc/.vim/plugged/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Invalid buffer id: 682
```

**Comment by ms-jpq** [comment]
fixed 8fb43c26b7f2723449b5c0206ad5d2be3396d5ed
