### ISSUE TITLE
Incompatibility with Python 3.11

### ISSUE THREAD

**Issue by martymichal** [ms-jpq/coq_nvim#528]
Invoking the completion popup and then traversing it with <Tab> or <Arrow Down> causes the following error to show up repeatedly:

```
Passing coroutines is forbidden, use tasks explicitly.
Traceback (most recent call last):
  File "/var/home/marty/.local/share/nvim/plugged/coq_nvim/.vars/runtime/lib64/python3.11/site-packages/pynvim_pp/logging.py", line 31, in suppress_and_log
    yield None
  File "/var/home/marty/.local/share/nvim/plugged/coq_nvim/coq/server/registrants/preview.py", line 236, in cont
    done, _ = await wait(
              ^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 420, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

Output of `nvim --version`
```
NVIM v0.8.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.0/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.8.0/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.0/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.0/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Output of `python3 --version`:
```
Python 3.11.0rc2
```

Ran in a container based on Fedora 37 using [Toolbx](https://github.com/containers/toolbox).

**Comment by maxwelljens** [comment]
Does anyone know if there is a way to change which Python engine Neovim uses, so this can be temporarily worked around?

**Comment by ms-jpq** [comment]
fixed
