### ISSUE TITLE
frozen runpy

### ISSUE THREAD

**Issue by Nicolas7102** [ms-jpq/coq_nvim#589]
I keep getting this error after installing it and downloading the dependencies

Traceback (most recent call last):                                                                                                              File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\__main__.py", line 175, in &lt;module&gt;
    arun(init(args.socket, ppid=args.ppid))
  File "C:\Users\Nico\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\client.py", line 72, in init
    stk = await stack()
          ^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\server\runtime.py", line 128, in stack
    idb = IDB()
          ^^^^^
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\databases\insertions\database.py", line 41, in __init__
    self._conn: Connection = self._ex.ssubmit(_init)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\shared\executor.py", line 48, in ssubmit
    result = cast(_T, fut.result())
                      ^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\shared\executor.py", line 35, in cont
    ret = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nico\AppData\Local\nvim-data\site\pack\packer\start\coq_nvim\coq\databases\insertions\database.py", line 33, in _init
    conn.executescript(sql("create", "pragma"))
sqlite3.OperationalError: near ".": syntax error
*It looks a little different here in github, here is the original https://jpst.it/3iGBq *

I have no idea what i'm doing wrong. Any help is appreciated.

**Comment by PsychedelicShayna** [comment]
I'm having the exact same issue, our outputs look identical. We both happen to be on Windows as well. How did you acquire the `sqlite3` dependency? If I'd have to guess, that's probably where the issue stems from. I personally just used `choco` to install it, i.e. `choco install sqlite`, and have version 3.42.0 installed.
```
sqlite3.exe --version
3.42.0 2023-05-16 12:36:15 831d0fb2836b71c9bc51067c49fee4b8f18047814f2ff22d817d25195cf350b0
```
What about you? 

I also do not seem to have the headers & source included on my system for sqlite3, at least not as a result of installing it through `choco`, which when acquiring `pysqlite` via `python -m pip install pysqlite3`, causes the build to fail:
```
pip-install-4rf6p7vt\pysqlite3_bc844391c2da47b8a4e8d89e8c947f04\src\blob.h(4): fatal error C1083: Cannot open include file: 'sqlite3.h': No such file or directory
```
This may have something to do with the problem. Do your results differ?

[Related SO Question, Might Help](https://stackoverflow.com/questions/54876404/unable-to-import-sqlite3-using-anaconda-python/55642416#55642416)

I'm going to do a bit more research in the meantime, and try to figure out what is causing:
```
conn.executescript(sql("create", "pragma"))
sqlite3.OperationalError: near ".": syntax error
```
and try reproducing it myself in a toybox environment. 

I'm also going to try and see if I have any luck using older `coq_nvim` commits (so far, I don't think I went back far enough. I did get a different error though, or rather, no output, and a permission error in the old error's place, which didn't make any sense. I don't have it on hand, as I switched back to head, but I will post an update containing the other error, alongside any relevant findings as I continue to debug this) 

One more thing, do you also happen to be using Lazy as your plugin manager? I'm unsure where I saw it, but in one of the stack traces, I did see a mention of Packer failing to be imported/included (unsure if it was Lua or Python). I'll try reproducing that again, but given [this other issue](https://github.com/ms-jpq/coq_nvim/issues/549), perhaps Lazy might also be a contributing factor?

I wonder why this is such a recent issue; hasn't anyone attempted to install `coq_nvim` on Windows before now? _Something_ must have changed, no?

**Comment by HSadeghein** [comment]
I have the same problem. I use `packer` as my plugin manager. I tried to use the older commits but I got some dependency errors.
I think there is some syntax problem in the query that it's passed to `executescript`

**Comment by 54m43lJ** [comment]
This seems to be a problem with symlinks. The sql script it is trying to call is a symbolic link, but it seems you have to explicitly specify `core.symlinks` as `true` to create the symlink when cloning, which vimplug does not do. For anyone using `vimplug` my quick solution is just go into the `nvim-data/plugged` folder, remove the `coq_nvim` directory, open any terminal as administrator (e.g. CMD, Windows Powershell, Git Bash) and manually clone the repo with `git -c core.symlinks=true clone https://github.com/ms-jpq/coq_nvim.git`.

**Comment by refleraga** [comment]
> remove the `coq_nvim` directory, open any terminal as administrator (e.g. CMD, Windows Powershell, Git Bash) and manually clone the repo with `git -c core.symlinks=true clone https://github.com/ms-jpq/coq_nvim.git`

This worked! In my case I use lazy.nvim so the `coq_nvim` directory was in `nvim-data/lazy/` instead. Thanks @54m43lJ!

**Comment by Nicolas7102** [comment]
> This seems to be a problem with symlinks. The sql script it is trying to call is a symbolic link, but it seems you have to explicitly specify `core.symlinks` as `true` to create the symlink when cloning, which vimplug does not do. For anyone using `vimplug` my quick solution is just go into the `nvim-data/plugged` folder, remove the `coq_nvim` directory, open any terminal as administrator (e.g. CMD, Windows Powershell, Git Bash) and manually clone the repo with `git -c core.symlinks=true clone https://github.com/ms-jpq/coq_nvim.git`.

This instantly solved the problem. Thank you so much!!

**Comment by Kethku** [comment]
Running into this as well after updating. I've been using coq_nvim for a year or so now before this issue so it seems like something recent.

Will try the above solution

**Comment by kuator** [comment]
> 

neovide is pretty cool, btw

**Comment by k3dr1** [comment]
> This seems to be a problem with symlinks. The sql script it is trying to call is a symbolic link, but it seems you have to explicitly specify `core.symlinks` as `true` to create the symlink when cloning, which vimplug does not do. For anyone using `vimplug` my quick solution is just go into the `nvim-data/plugged` folder, remove the `coq_nvim` directory, open any terminal as administrator (e.g. CMD, Windows Powershell, Git Bash) and manually clone the repo with `git -c core.symlinks=true clone https://github.com/ms-jpq/coq_nvim.git`.

thank you so much, helped!!!

**Comment by phuertay** [comment]
The current solution seems to require admin rights (to create the symbolic links). Does anyone know if there's an alternative without them?

**Comment by TomzBench** [comment]
> This seems to be a problem with symlinks. The sql script it is trying to call is a symbolic link, but it seems you have to explicitly specify `core.symlinks` as `true` to create the symlink when cloning, which vimplug does not do. For anyone using `vimplug` my quick solution is just go into the `nvim-data/plugged` folder, remove the `coq_nvim` directory, open any terminal as administrator (e.g. CMD, Windows Powershell, Git Bash) and manually clone the repo with `git -c core.symlinks=true clone https://github.com/ms-jpq/coq_nvim.git`.

Woohoo! thank you!

> The current solution seems to require admin rights (to create the symbolic links). Does anyone know if there's an alternative without them?

The problem i guess is vim-plug?  perhaps there is a better neovim native one that somebody can recommend known to work with symlinks on windows?

**Comment by camAtGitHub** [comment]
Regarding the non-admin symlink work around for Windows users... 

- Install the plugin as per normal then exit neovim.
- Find the 'coq_nvim' folder your nvim plugin managed created.
-   You should see folders like 'artifacts', 'autoload', 'ci' etc etc
- make a bat file called 'symlink-workaround.bat' with the contents below and save in under the 'coq_nvim' directory (eg. 'coq_nvim\symlink-workaround.bat`)

```
:: symlink-workaround.bat
cd /d "%~dp0"
copy  coq\clients\buffers\db\sql\create\pragma.sql coq\clients\cache\db\sql\create\pragma.sql 
copy  coq\clients\buffers\db\sql\create\pragma.sql coq\clients\registers\db\sql\create\pragma.sql 
copy  coq\clients\snippet\db\sql\create\pragma.sql coq\clients\tags\db\sql\create\pragma.sql 
copy  coq\clients\buffers\db\sql\create\pragma.sql coq\clients\tmux\db\sql\create\pragma.sql 
copy  coq\clients\buffers\db\sql\create\pragma.sql coq\clients\tree_sitter\db\sql\create\pragma.sql 
copy  coq\clients\buffers\db\sql\create\pragma.sql coq\databases\insertions\sql\create\pragma.sql 
copy coq\server\completion.lua lua\coq\completion.lua 
copy coq\lsp\requests\lsp.lua lua\coq\lsp-request.lua 
copy coq\treesitter\request.lua lua\coq\ts-request.lua 
```

- Then run the bat file by double clicking it / via command prompt etc.

Unfortunately this is a temp fix that will break when ever more symlinks are added / moved etc.
Also when ever some package managers 'sync' the copied files will be gone (Jetpack I'm looking at you), so You might want to add a 'do' action thing in your vim-plug config etc to call that bat file - but Ill leave that as an exercise for the reader.
