### ISSUE TITLE
Can't start coq on Windows. Sqlite syntax error

### ISSUE THREAD

**Issue by OrangeLightning219** [ms-jpq/coq_nvim#604]
Hi. I just installed coq and according to the instructions I'm running the COQdeps and COQnow commands. COQdeps worked fine but running COQnow throws this error (I'm using python 3.12):

```
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\__main__.py", line 175, in <module>


    arun(init(args.socket, ppid=args.ppid))

  File "C:\Program Files\Python\Lib\asyncio\runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "C:\Program Files\Python\Lib\asyncio\runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Program Files\Python\Lib\asyncio\base_events.py", line 664, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\client.py", line 72, in init

    stk = await stack()

          ^^^^^^^^^^^^^

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\server\runtime.py", line 128, in stack

    idb = IDB()

          ^^^^^

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\databases\insertions\database.py", line 41, in __init__

    self._conn: Connection = self._ex.ssubmit(_init)

                             ^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\shared\executor.py", line 48, in ssubmit

    result = cast(_T, fut.result())

                      ^^^^^^^^^^^^

  File "C:\Program Files\Python\Lib\concurrent\futures\_base.py", line 456, in result

    return self.__get_result()

           ^^^^^^^^^^^^^^^^^^^

  File "C:\Program Files\Python\Lib\concurrent\futures\_base.py", line 401, in __get_result

    raise self._exception

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\shared\executor.py", line 35, in cont

    ret = f(*args, **kwargs)

          ^^^^^^^^^^^^^^^^^^

  File "C:\Users\marce\AppData\Local\nvim-data\lazy\coq_nvim\coq\databases\insertions\database.py", line 33, in _init

    conn.executescript(sql("create", "pragma"))

sqlite3.OperationalError: near ".": syntax error



COQ EXITED - 1

```

**Comment by LBdN** [comment]
same error.

**Comment by TomzBench** [comment]
@OrangeLightning219 @LBdN 

This issue is also (poorly titled) here https://github.com/ms-jpq/coq_nvim/issues/589

The solution is noted in there too, which is basically manually clone the repo with core.symlines=true. Which plugin managers don't do and also because you need admin rights (which is unfortunate for this workaround).

Since this workaround is not practical im currently using a different completer plugin until this is fixed. I think the solution is to remove the symlink stuff because that is too fancy for windows
