### ISSUE TITLE
COQ exited -1 on nvim launch

### ISSUE THREAD

**Issue by oc-tk** [ms-jpq/coq_nvim#615]
Trying to setup COQ with rustaceanvim + lspconfig.
I was able to run :COQdep and update all and I cannot run :COQnow
[My config](https://github.com/oc-tk/nvimcfg)
I just want to have rust LSP + autocompletion but I am utter noob if we are talking about configuring nvim.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\__main__.py", line 175, in <module>
    arun(init(args.socket, ppid=args.ppid))
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\client.py", line 72, in init
    stk = await stack()
          ^^^^^^^^^^^^^
  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\server\runtime.py", line 128, in stack

    idb = IDB()
          ^^^^^
  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\databases\insertions\database.py", line 41, in __init__
    self._conn: Connection = self._ex.ssubmit(_init)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\shared\executor.py", line 48, in ssubmit

    result = cast(_T, fut.result())
                      ^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 456, in result

    return self.__get_result()

           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result

    raise self._exception
  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\shared\executor.py", line 35, in cont

    ret = f(*args, **kwargs)

          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\TK\AppData\Local\nvim-data\lazy\coq_nvim\coq\databases\insertions\database.py", line 33, in _init

    conn.executescript(sql("create", "pragma"))

sqlite3.OperationalError: near ".": syntax error


COQ EXITED - 1
```

**Comment by DanielMichel305** [comment]
Did you manage to fix it? I'm getting the exact same error.

**Comment by Klvxn** [comment]
currently having the same issue. no fix yet??

**Comment by Klvxn** [comment]
Found a fix [https://github.com/ms-jpq/coq_nvim/issues/589#issuecomment-1651436348](https://github.com/ms-jpq/coq_nvim/issues/589#issuecomment-1651436348)
