### ISSUE TITLE
TMUX crashes coq_nvim

### ISSUE THREAD

**Issue by samrathchadha** [ms-jpq/coq_nvim#622]
my configuration is virtually nothing but

```
require("coq_3p")({
  { src = "nvimlua", short_name = "nLUA" },
  { src = "vimtex", short_name = "vTEX" },
  { src = "copilot", short_name = "COP", accept_key = "<c-r>" },
})
```

the error:
```
not enough values to unpack (expected 7, got 1)
Traceback (most recent call last):
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.
11/site-packages/pynvim_pp/logging.py", line 31, in suppress_and_log
    yield None
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/tmux/worker.py
", line 41, in _poll
    await self.periodical()
           ^^^^^^^^^^^^^
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/tmux/parse.py", line 5
9, in cont
    (
ValueError: not enough values to unpack (expected 7, got 1)
not enough values to unpack (expected 7, got 1)
Traceback (most recent call last):
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.
11/site-packages/pynvim_pp/logging.py", line 31, in suppress_and_log
    yield None
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/tmux/worker.py
", line 41, in _poll
    await self.periodical()
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/tmux/worker.py
", line 49, in periodical
    current, panes = await snapshot(
                     ^^^^^^^^^^^^^^^
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/tmux/parse.py", line 1
13, in snapshot
    panes = await _panes(tmux, all_sessions=all_sessions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/tmux/worker.py
", line 41, in _poll
    await self.periodical()
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/tmux/worker.py
", line 49, in periodical
    current, panes = await snapshot(
                     ^^^^^^^^^^^^^^^
  File "/Users/sam/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/tmux/parse.py", line 1
13, in snapshot
    panes = await _panes(tmux, all_sessions=all_sessions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-- More --
```
https://github.com/ms-jpq/coq_nvim/assets/69572668/89b6d260-5e8d-4ffd-9a3e-93ae5a07c144

**Comment by btittelbach** [comment]
I can confirm this bug

**Comment by PavelSolaris** [comment]
The commit 649443f solved the issue

**Comment by btittelbach** [comment]
fix confirmed. Weird though that Lazy update did not fix this and I had to pull manually.
