### ISSUE TITLE
TypeError: conn() got multiple values for argument 'socket'

### ISSUE THREAD

**Issue by LoCrealloc** [ms-jpq/coq_nvim#628]
Hey there, I wanted to try out this plugin, but unfortunately, it does not even launch for me..

I installed the plugin on my system using the Nix package manager, but whenever I try to run any command, coq just fails giving me the following error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/nix/store/sxrg2s6i8mfw90xkhs7vzxcdv7dbxdki-vimplugin-coq_nvim-2024-03-11/coq/__main__.py", line 177, in <module>
    arun(init(args.socket, ppid=args.ppid, th=th))
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/sxrg2s6i8mfw90xkhs7vzxcdv7dbxdki-vimplugin-coq_nvim-2024-03-11/coq/client.py", line 102, in init
    await gather(wrap_future(die), cont())
  File "/nix/store/sxrg2s6i8mfw90xkhs7vzxcdv7dbxdki-vimplugin-coq_nvim-2024-03-11/coq/client.py", line 76, in cont
    async with conn(die, socket=socket, default=_default) as client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/contextlib.py", line 334, in helper
    return _AsyncGeneratorContextManager(func, args, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/contextlib.py", line 105, in __init__
    self.gen = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
TypeError: conn() got multiple values for argument 'socket'
```

Hope that this can get fixed, coq looks really promising to me!

**Comment by LoCrealloc** [comment]
Apparently, this has been fixed in the meantime, I can now run coq_nvim on NixOS.
