### ISSUE TITLE
Random error popup

### ISSUE THREAD

**Issue by SamuelTJackson** [ms-jpq/coq_nvim#77]
Hey,
I get the following error randomly. I could not figure out why it's happening.

my coq config:
```lua
local g = vim.g
g.coq_settings = {
    keymap = {jump_to_mark = "<C-p>"},
    display = {pum = {source_context = {"[", "]"}}}

}
```
packer:
```lua
    use {
        'neovim/nvim-lspconfig',
        config = function() require('nvim.plugins.lsp') end,
        requires = {
            {'ms-jpq/coq_nvim', branch = 'coq'},
            {'ms-jpq/coq.artifacts', branch = 'artifacts'}
        }
    }
```

![image](https://user-images.githubusercontent.com/14303082/129800933-710cf3de-009a-46f0-a7f4-9907053d055f.png)

```
Traceback (most recent call last):
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/logging.py", line 31, in with_suppress                                                           
    yield None
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/shared/runtime.py", line 152, in cont
    assert not self._lock.locked()
AssertionError
Press ENTER or type command to continue
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/logging.py", line 31, in with_suppress
    yield None
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 21, in wrapper
    return await aw
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/registrants/omnifunc.py", line 54, in c0
    vim_comps = tuple(trans(stack, context=ctx, metrics=metrics))
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/trans.py", line 148, in trans
    w_adjust = _cum(stack.settings.weights, metrics=metrics)
  File "/home/samuel/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/trans.py", line 25, in _cum
    for metric in metrics:
TypeError: 'NoneType' object is not iterable
```

**Comment by ms-jpq** [comment]
oh shoot, i must have introduced a race error, sorry.

ill push a hotfix for you and look into it deeper later.

**Comment by ms-jpq** [comment]
hot fix is pushed

**Comment by SamuelTJackson** [comment]
Nice fixed! Thank you very much.
