### ISSUE TITLE
Various completion glitches

### ISSUE THREAD

**Issue by YodaEmbedding** [ms-jpq/coq_nvim#99]
## Reproducible environment

Copy and paste this into your terminal:

```bash
mkdir -p ~/.local/share/nvim/site/pack/bundle
cd ~/.local/share/nvim/site/pack/bundle
git clone https://github.com/neovim/nvim-lspconfig
git clone https://github.com/ms-jpq/coq_nvim
echo '
let $PLUGIN_DIRECTORY = "~/.local/share/nvim/site/pack/bundle"
set runtimepath^=$PLUGIN_DIRECTORY/nvim-lspconfig
set runtimepath^=$PLUGIN_DIRECTORY/coq_nvim

lua << EOF
local nvim_lsp = require("lspconfig")
local coq = require("coq")
nvim_lsp.pyright.setup {}
vim.cmd [[COQdeps]]
vim.cmd [[COQnow -s]]
EOF
' > ~/init_tmp.vim
nvim --clean -u ~/init_tmp.vim tmp.py
```

## Test cases

1. `idefault<Tab><CR><Esc>`
   
   **Expected:**
   ```python
   from collections import defaultdict
   
   
   defaultdict
   ```
   
   **Actual:**
   ```python
   from collections import defaultdict
   
   
   default
   ```
   
2. `idefaultdict<Esc>Icollect<Tab><CR>.<Esc>`
   
   **Expected:**
   ```python
   import collections
   
   
   collections.defaultdict
   ```
   
   **Actual:**
   ```python
   import collections
   
   
   collectdefa.ultdict
   ```
   
3. `iimport collections<CR><CR>defaultdict<Esc>Icollect<Tab><CR>.<Esc>`
   
   **Expected:**
   ```python
   import collections
   
   
   collections.defaultdict
   ```
   
   **Actual:**
   ```python
   import collections
   
   
   collections.
   ```
   
4. `ihello<CR>hello<Esc>*cgnimp<C-n><CR><Esc>.`
   
   **Expected:**
   ```python
   import
   import
   ```
   
   **Actual:**
   ```python
   import
   imp
   ```
   
   (Adapted from: https://github.com/ms-jpq/coq_nvim/issues/47.)

I think the first two only happen in new and empty files. The third and fourth ones are the important ones since they happen very often in non-empty files.

**Comment by ms-jpq** [comment]
thank you this is gonna be next PR

**Comment by ms-jpq** [comment]
i think most of the issues come from the fact that I I didn't write my code to handle multiple edits on the same line, which happens for 1) and 2).

the `.` one might not be doable, at least not without hampering fuzzy searching

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/130 fixes 1) and 2), but the `.` still needs investigating

**Comment by dtomvan** [comment]
If I complete anything (including snippets), coq spits out complete nonsense. Help?

**Comment by ms-jpq** [comment]
please post a screenshot, i dont know what do you mean by that

**Comment by YodaEmbedding** [comment]
@dtomvan It might be better to create a [new issue](https://github.com/ms-jpq/coq_nvim/issues/new) since it might not be related to these.

**Comment by dtomvan** [comment]
Im’ma make a GIF in a new issue.

Edit: in a couple of hours

**Comment by dtomvan** [comment]
This is https://github.com/ms-jpq/coq_nvim/issues/34?

**Comment by dtomvan** [comment]
Okay, now I have this output. My coq install seems very broken.
```
end_col out of bounds
Traceback (most recent call last):
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_
pp/logging.py", line 31, in with_suppress
    yield None
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_
pp/lib.py", line 43, in wrapper
    return await aw
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/registrants/omnifunc.py", line 189, in
 cont
    inserted = await async_call(
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_
pp/lib.py", line 83, in async_call
    return await loop.run_in_executor(None, fut.result)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_
pp/lib.py", line 74, in cont
    ret = fn(*args, **kwargs)
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/registrants/omnifunc.py", line 191, in
 <lambda>
    lambda: edit(
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/edit.py", line 372, in edit
    inserted = _restore(nvim, buf=buf, pos=state.context.position, before=before)
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/edit.py", line 356, in _restore
    nvim.api.buf_set_text(buf, row, l1, row, h1, (replace,))
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim/
api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/tomvd/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim/
msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: end_col out of bounds
```
Edit: my configs: https://github.com/dtomvan/.config
Edit: I changed my configs to temporarily not include any auto pairs plugin. coq just lags out when I try to use it tho.

**Comment by dtomvan** [comment]
Video: https://imgur.com/z09aJSs
